Repository replaysMike/TypeSupport, pull requests merged in 2019-05, with the labels that each got.

#13 In a Blazor app the _propertyInfo.GetGetMethod(true) can return null
  TypeSupport/TypeSupport/ExtendedProperty.cs
Labels: bug, good first issue

#18 Fixes #17 - AmbiguousMatchException thrown
  TypeSupport/TypeSupport.Tests/TestObjects/InheritedObject.cs
  TypeSupport/TypeSupport.Tests/TypeSupportTests.cs
  TypeSupport/TypeSupport/ExtendedField.cs
  TypeSupport/TypeSupport/Extensions/ObjectExtensions.cs
  TypeSupport/TypeSupport/Extensions/TypeExtensions.cs
Labels: bug

#19 adds build scripts for AppVeyor support in the repo
  appveyor.yml
  scripts/build.ps1
  scripts/run-tests.ps1
  scripts/send-coverage.ps1
Labels: enhancement
